Fix service tier import duplication
alphagov/local-links-manager pull request #104
Opened 2016-12-06 16:15 UTC by emmabeynon

Trello card: https://trello.com/c/IbaS4EjW/581-fix-servicetier-import-to-not-create-duplicates

This updates the ServiceTierImporter to not import duplicate ServiceTiers, and removes the rake task that deletes ServiceTier duplicates.

2016-12-06 18:08 UTC, davidbasalla requested changes
I think there might still be an issue when the tiers for a Service change (eg from 'county/unitary' to 'district/unitary') which I don't think is handled by this code. The Service importer has a `create_or_update_record` method which (in concept) might be more appropriate here? 

Let's have a chat tomorrow as I'm a bit unclear on why we do this import from Publisher anyway. Feels like LocalLinksManager could be the source of truth for this data...?

2016-12-07 14:41 UTC, emmabeynon commented
Hi @davidbasalla, the first commit is now updated to handle services whose tiers change.

2016-12-09 10:31 UTC, brenetic commented
👍  This looks good to me. @davidbasalla has more context but FFTM

2016-12-09 10:58 UTC, whoojemaflip commented
It might be a good idea to add some validation to the `ServiceTier` model, which would ensure no duplicates could be created without throwing an error.

2016-12-09 11:04 UTC, whoojemaflip requested changes

2016-12-09 11:04 UTC, whoojemaflip commented on lib/local-links-manager/import/services_tier_importer.rb
> +          if service.tiers.include?('district')
This class is modifying data related to the `Service` class a lot. Maybe indicative of [feature envy](https://sourcemaking.com/refactoring/smells/feature-envy). Could this logic live in the `Service` class instead?

2016-12-12 14:33 UTC, whoojemaflip commented on lib/local-links-manager/import/services_tier_importer.rb
> +          service.delete_and_create_tiers(item[:tier])
If this is run for every service, then all the `created_at` timestamps will be the same, right?

2016-12-12 14:43 UTC, whoojemaflip commented
is this missing a migration?

2016-12-12 14:46 UTC, emmabeynon commented
@whoojemaflip whoops, not sure where that went! Should be in the last commit now.

2016-12-12 14:54 UTC, whoojemaflip approved these changes

2016-12-13 09:57 UTC, merged