Update edit link page
alphagov/local-links-manager pull request #91
Opened 2016-11-24 14:48 UTC by brenetic

- The edit link page now has both the service title and the interaction
title
- 'LGSL code' is now 'Service code'
- Removed LGIL
- 'URL' is now 'Page URL'
- Removed the ability to edit the homepage url

# Before

<img width="1172" alt="before" src="https://cloud.githubusercontent.com/assets/3466862/20602414/f584cfee-b254-11e6-8e5d-1720cae02bc3.png">

# After

<img width="1167" alt="after" src="https://cloud.githubusercontent.com/assets/3466862/20602420/fab12e0e-b254-11e6-8ec4-b2af8bc0cc1e.png">

[Trello card](https://trello.com/c/gh6xcdeY/564-update-edit-links-and-add-link-pages-2)

2016-11-24 14:49 UTC, brenetic commented
The commit for e98b2fbfefdd51ca48b9bd2190cd66b8665ad70e will be removed once https://github.com/alphagov/local-links-manager/pull/91 has been merged

2016-11-25 11:06 UTC, issyl0 commented on app/views/links/edit.html.erb
> +      <p class="text-muted">example http://www.local-authority.gov.uk</p>
ISTR this should be "for example".

2016-11-29 11:40 UTC, whoojemaflip requested changes

2016-11-29 11:40 UTC, whoojemaflip commented on app/controllers/links_controller.rb
>    def redirect(action = 'saved')
Could this be called `redirect_back` to give a clearer idea of what it's doing?

2016-11-29 11:40 UTC, whoojemaflip commented on app/views/interactions/index.html.erb
> +        <% if flash[:updated].present? &&
if only there were some kind of Presenter to delegate this logic to...

2016-11-29 11:40 UTC, whoojemaflip commented on app/views/links/edit.html.erb
> +      <%= link_to 'Cancel', flash[:back], class: 'btn btn-default add-right-margin' %>
instead of using `flash[:back]` here, would it be possible to use a helper method to wrap this functionality, and provide a fallback?

2016-11-29 11:40 UTC, whoojemaflip commented on app/controllers/links_controller.rb
> +    flash[:link_url] = params[:link][:url].strip
There's some duplication of `params[:link][:url].strip` - could this be extracted into a method?

2016-11-29 11:40 UTC, whoojemaflip commented on app/presenters/url_status_presentation.rb
> +  def updated_url?
It might be more idiomatic to call this `updated?`

2016-11-29 11:40 UTC, whoojemaflip commented on spec/features/local_authorities/local_authority_show_spec.rb
> +        expect(page).to have_link('http://angus.example.com/link-to-change')
Would this test pass if the page just reloaded?  What about an assertion on the URL?

2016-11-29 11:40 UTC, whoojemaflip commented on app/controllers/links_controller.rb
> +  before_action :load_dependencies, :set_back_url_before_post_request
is this relevant to all controller methods, or could it be restricted to just one or two?

2016-11-29 18:31 UTC, brenetic commented
@whoojemaflip  Addressed all the comments and did most of the refactor for the `Links#index`. Unfortunately one set of failing tests remain . . . 💥 🔥 👎

2016-11-30 10:52 UTC, issyl0 commented
Are the tests failing because there's a trailing `:` in `(def initialize(link, view_context:)` that it then can't find `view_context` without the `:` in the method itself? *shrug*

2016-11-30 10:52 UTC, davidbasalla commented
Could we split that out that last commit into a different PR? It seems like a substantial change which is not directly related to the 'edit link' page

2016-11-30 11:02 UTC, brenetic commented
@issyl0 the `view_context` is a named parameter

2016-11-30 11:13 UTC, brenetic commented
@davidbasalla  Removed the last commit. Will raise another PR

2016-11-30 11:43 UTC, whoojemaflip commented on app/controllers/links_controller.rb
> +  before_action :set_back_url_before_post_request, only: [:edit, :update, :destroy]
this might be more succinctly expressed as
`before_action :set_back_url, if: -> { request.post? }`

NBD though, only change it if you want to.

2016-11-30 11:45 UTC, whoojemaflip approved these changes
Cool cool cool

2016-11-30 11:47 UTC, merged